apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: myjob
    spec:
     restartPolicy: OnFailure
     containers:
      - name: main
        image: luksa/batch-job
