apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  completions: 6
  parallelism: 3
  template:
    metadata:
      labels:
        app: myjob
    spec:
     restartPolicy: OnFailure
     containers:
      - name: main
        image: luksa/batch-job
