apiVersion: v1
kind: PersistentVolume
metadata:
  name: awspv
  labels:
    app: dev
spec:
  capacity:
   storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
   server: "fs-05d78a4df80c38d45.efs.us-east-1.amazonaws.com"
   path: /test
