apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcclaim1
  labels:
    app: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: dev
