apiVersion: v1
kind: ReplicationController
metadata:
 name: mynginxpod1
spec:
 replicas: 1 
 template:
   metadata:
     labels:
       app: dev
   spec:
     containers:
        - image: nginx
          name: nginxcontainer
          ports:
            - containerPort: 80
