services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Sahil#99
      MYSQL_DATABASE: newdb
    ports:
      - 3306
    volumes:
      - /home/ec2-user/fanstorage:/var/lib/mysql
    networks:
      - backend

  web:
    image: nginx
    depends_on:
      - db
    ports:
      - 80:80
    volumes:
      - /home/ec2-user/bye:/usr/share/nginx/html
    networks:
      - frontend

  app:
    image: php:7.4-fpm
    depends_on:
      - db
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
