services:
 db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: Pass@123
    MYSQL_DATABASE: wordpressdb
  ports:
   - 3306
  volumes:
   - /home/ec2-user/bi:/var/lib/mysql
  networks:
   - backend

 web:
  image: php:7.4-apache
  ports:
   - 80:80
  depends_on:
   - db
  volumes:
   - /home/ec2-user/bye:/var/www/html  # Mapping a volume from host to container
  networks:
   - frontend

 app:
  image: php:7.4-fpm
  depends_on:
   - db
  networks:
   - frontend
   - backend

networks:
  frontend:
  backend:

