apiVersion: v1
kind: Pod
metadata:
  name: mypodnginx
  labels:
    hiii: bye
spec:
  nodeSelector:
    work: "one"
  containers:
    - image: nginx
      name: bababababa
      ports:
        - containerPort: 80

