apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrspod
spec:
  replicas: 3
  selector:
    matchExpression:
      key: app
      operator: In
      value:
        - dev
        - live
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - image: nginx
          name: ngcontainer
          ports:
            - containerPort: 80
