apiVersion: v1
kind: Pod
metadata:
 name: mynginxpod111
 labels:
   app: dev
spec:
 nodeSelector:
     work: "one"
 containers:
   - image: nginx
     name: mynginxcontainer
     ports:
       - containerPort: 80
