apiVersion: v1
kind: ReplicationController
metadata:
  name: livenessrc
spec:
  replicas: 4
  template:
    metadata:
     labels:
      app: caca
    spec:
     containers:
      - image: nginx
        name: ngcont
        ports:
         - containerPort: 80
        livenessProbe:
         httpGet:
          path: /index.html
          port: 80
         periodSeconds: 10
         initialDelaySeconds: 10  
