apiVersion: v1
kind: ReplicationController
metadata:
  name: hamarrc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        jj: kk
    spec:
      containers:
        - image: nginx
          name: sahilcont
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 10
