apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicationcontrollllll
spec:
  replicas: 3
  template:
    metadata:
      labels:
        amdi: melody
    spec:
      containers:
        - image: nginx
          name: myncontainer
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 10
