apiVersion: v1
kind: ReplicationController
metadata:
  name: lasanrc
spec:
  replicas: 4
  template:
    metadata:
      labels:
        gan: machine
    spec:
      containers:
        - image: nginx
          name: ngcontll
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 10
