apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplicationcontroller
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - image: nginx
          name: myngic
          ports:
            - containerPort: 80
